stages:
  - lint
  - test
  - build

variables:
  NPM_CACHE_KEY: "$CI_COMMIT_REF_NAME"

lint:
  stage: lint
  image: node:16
  script:
    - npm install
    - npm run lint
  cache:
    key: "$NPM_CACHE_KEY"
    paths:
      - node_modules/
  rules:
    - exists:
        - "*.js"
        - "*.css"

test:
  stage: test
  image: node:16
  script:
    - npm install
    - npm run test:jest
  cache:
    key: "$NPM_CACHE_KEY"
    paths:
      - node_modules/
  rules:
    - exists:
        - "*.js"

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  artifacts:
    paths:
      - dist/
